Repository kinming92/django-polls-app, pull requests merged in 2021-09, with the labels that each got.

#1 first commit of polls app
  Readme.md
  mysite/manage.py
  mysite/mysite/__init__.py
  mysite/mysite/asgi.py
  mysite/mysite/settings.py
  mysite/mysite/urls.py
  mysite/mysite/wsgi.py
  mysite/polls/__init__.py
  mysite/polls/admin.py
  mysite/polls/apps.py
  mysite/polls/migrations/__init__.py
  mysite/polls/models.py
  mysite/polls/tests.py
  mysite/polls/urls.py
  mysite/polls/views.py
Labels: enhancement

#5 fixed the feather C
  mysite/mysite/settings.py
Labels: bug

#6 changes for featureB
  mysite/polls/admin.py
  mysite/polls/models.py
Labels: bug, enhancement
